services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - order-db-data:/app/instance
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development

volumes:
  order-db-data:
