name: Main workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          cd backend
          pip install -r requirements.txt

      - name: Lint with ruff
        run: |
          cd backend
          ruff check .

      - name: Set up test enviroment
        run: |
          cd backend
          mkdir -p instance

      - name: Test with unittest
        run: |
          cd backend
          python -m unittest discover -s tests
